### ISSUE TITLE
Feature request: Associative array pattern

### ISSUE THREAD

**Issue by wata727** [sider/phinder#46]
Currently, PHP doesn't support keyword (named) arguments. As a result, some methods may accept options as associative arrays. The following is an example:

```php
<?php

function addKey(string $body, array $options) {
  // Implementation here...
}

addKey("...", ['type' => 'rsa', 'passphrase' => 'super secret']);
```

Considering such a case, associative array pattern syntax helps us to find code pieces like calling a function without important options. Probably, this syntax should be similar to [Querly's keyword argument patterns](https://github.com/soutaro/querly/blob/master/manual/patterns.md#kwargs).

```
addKey(_, 'type' => 'rsa') # Matches if a second argument has a key-value pair of 'type' and 'rsa'
addKey(_, !'type' => _) # Matches if a second argument doesn't have a key of 'type'
```

The above syntax is an example. A better syntax may be found. What do you think?

**Comment by tomokinakamaru** [comment]
@wata727 The existence of a key can be checked in the current implementation. For instance, the pattern `addKey(_, ['type' => 'rsa'])` captures the PHP code `addKey('...', ['type' => 'rsa'])`.

However, to achieve your goal, there remain two problems in the current implementation:

(1) The pattern `addKey(_, ['type' => 'rsa'])` does not capture the PHP code `addKey('...', ['type' => 'rsa', 'passphrase' => 'super secret'])` because the pattern indicates that the second argument is exactly `['type' => 'rsa']`.

(2) There is no way to assert the non-existence.

--

For Problem (1), I am planning to slightly change the semantics of `...` inside `[]`, for example as follows:
```php
// Matches `addKey('...', ['type' => 'rsa'])`
// but does not match `addKey('...', ['type' => 'rsa', 'passphrase' => 'super secret'])`
addKey(_, ['type' => 'rsa']) 

// Matches `addKey('...', ['type' => 'rsa'])`
// and also matches `addKey('...', ['type' => 'rsa', 'passphrase' => 'super secret'])`
addKey(_, ['type' => 'rsa', ...]) 
```
This is like how we implemented in TyScan. Do you think this is acceptable syntax?

--

For Problem (2), we need to handle two kinds of negation: Non-existence of key, the value is not as expected. These two are natural to express as follows:
```
addKey(_, !'type' => _) // Non-existance of the key "type".
addKey(_, 'type' => !'rsa') // The value for the key "type" is not as expected.
```
Is this also acceptable? (Both of them can be achived only by allowing the negation operator `!` for any expression.)
